sonar.projectKey=bcgov_crt
sonar.organization=bcgov-sonarcloud

sonar.projectName=CaRT
# Path to sources
sonar.sources=api,client/src,twm
sonar.exclusions=**/node_modules/**,**/dist/**,**/bin/**,**/obj/**,**/coverage/**
#sonar.inclusions=

# Path to tests
sonar.tests=api/Crt.Tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.js,**/*Test.cs,**/*Tests.cs
#sonar.test.exclusions=

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=